### ISSUE TITLE
Add me as a contributor

### ISSUE THREAD

**Issue by davidfekke** [markradacz/HungerFreeCity#2]
Can you add me as a contributor? My github username is 'davidfekke'.

**Comment by sthornton** [comment]
Guess @markradacz must be so busy he cant add you.  I would if I could.

**Comment by markradacz** [comment]
done.. apologies for delay..  on vacation in Orlando.. ;)
hi Scott how ru?

**Comment by sthornton** [comment]
@markradacz I'm doing very well.  I was just messing with you by the way :-) .... I'll hit you up sometime soon to catch up.  Enjoy your vacation...
